
export const QUOTES = [
  { text: "Simplicity is the ultimate sophistication.", author: "Da Vinci" },
  { text: "Focus is a matter of deciding what things you're not going to do.", author: "Jobs" },
  { text: "Your mind is for having ideas, not holding them.", author: "Allen" },
  { text: "The secret of getting ahead is getting started.", author: "Twain" },
  { text: "Deep work is the superpower of the 21st century.", author: "Newport" },
  { text: "Action is the foundational key to all success.", author: "Picasso" },
  { text: "The best way to predict the future is to create it.", author: "Drucker" },
  { text: "Amor Fati. Love your fate.", author: "Nietzsche" },
  { text: "He who has a why to live can bear almost any how.", author: "Nietzsche" },
  { text: "Waste no more time arguing what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "The impediment to action advances action.", author: "Marcus Aurelius" },
  { text: "He who is brave is free.", author: "Seneca" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "The wise man does at once what the fool does at last.", author: "Baltasar Gracian" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Einstein" },
  { text: "The only way to do great work is to love what you do.", author: "Jobs" },
  { text: "Success is not final, failure is not fatal.", author: "Churchill" },
  { text: "You must be the change you wish to see in the world.", author: "Gandhi" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Out of your vulnerabilities will come your strength.", author: "Sigmund Freud" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Edison" },
  { text: "Whatever you are, be a good one.", author: "Lincoln" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Gandhi" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { text: "The beginning is the most important part of the work.", author: "Plato" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius" },
  { text: "Your days are numbered. Use them to throw open the windows of your soul.", author: "Marcus Aurelius" },
  { text: "Accept the things to which fate binds you.", author: "Marcus Aurelius" },
  { text: "Very little is needed to make a happy life.", author: "Marcus Aurelius" },
  { text: "To be calm is the highest achievement of the self.", author: "Zen Proverb" },
  { text: "Chop wood, carry water.", author: "Zen Proverb" },
  { text: "The obstacle is the path.", author: "Zen Proverb" },
  { text: "Move and the way will open.", author: "Zen Proverb" },
  { text: "The journey is the reward.", author: "Steve Jobs" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { text: "Greatness is a lot of small things done well.", author: "Ray Lewis" },
  { text: "Mastery requires patience.", author: "Robert Greene" },
  { text: "Patience is a bitter plant, but it has sweet fruit.", author: "Aristotle" },
  { text: "Consistency is better than perfection.", author: "Unknown" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "David Goggins" },
  { text: "Our focus is our future.", author: "Unknown" },
  { text: "The cave you fear to enter holds the treasure you seek.", author: "Joseph Campbell" },
  { text: "Art is the elimination of the unnecessary.", author: "Pablo Picasso" },
  { text: "Inspiration exists, but it has to find you working.", author: "Pablo Picasso" },
  { text: "Go confidently in the direction of your dreams.", author: "Thoreau" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Thoreau" },
  { text: "That which does not kill us makes us stronger.", author: "Nietzsche" },
  { text: "The higher we soar the smaller we appear to those who cannot fly.", author: "Nietzsche" },
  { text: "Sweat equity is the most valuable equity there is.", author: "Mark Cuban" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "By failing to prepare, you are preparing to fail.", author: "Benjamin Franklin" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle" },
  { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
  { text: "Quality means doing it right when no one is looking.", author: "Henry Ford" },
  { text: "Vision without execution is just hallucination.", author: "Thomas Edison" },
  { text: "Knowing is not enough; we must apply.", author: "Goethe" },
  { text: "The power of concentration is the only key.", author: "Vivekananda" },
  { text: "Take up one idea. Make that one idea your life.", author: "Vivekananda" },
  { text: "All power is within you; you can do anything and everything.", author: "Vivekananda" },
  { text: "Arise, awake, and stop not until the goal is reached.", author: "Vivekananda" },
  { text: "Freedom is the first condition of growth.", author: "Vivekananda" },
  { text: "Comfort is no test of truth. Truth is often far from being comfortable.", author: "Vivekananda" },
  { text: "Be a hero. Always say, I have no fear.", author: "Vivekananda" },
  { text: "The world is the great gymnasium where we come to make ourselves strong.", author: "Vivekananda" },
  { text: "Work is worship.", author: "Unknown" },
  { text: "Great thoughts speak only to the thoughtful mind.", author: "Theodore Roosevelt" },
  { text: "Man is made or unmade by himself.", author: "James Allen" },
  { text: "As a man thinketh in his heart, so is he.", author: "James Allen" },
  { text: "Dream lofty dreams, and as you dream, so shall you become.", author: "James Allen" },
  { text: "Self-control is strength. Right thought is mastery. Calmness is power.", author: "James Allen" },
  { text: "The law of harvest is to reap more than you sow.", author: "James Allen" },
  { text: "He who would accomplish little must sacrifice little.", author: "James Allen" },
  { text: "A strong man cannot help a weaker unless the weaker is willing.", author: "James Allen" },
  { text: "Calmness of mind is one of the beautiful jewels of wisdom.", author: "James Allen" },
  { text: "The man who does not work for the love of work but only for money.", author: "Charles Schwab" },
  { text: "Character is fate.", author: "Heraclitus" },
  { text: "No man ever steps in the same river twice.", author: "Heraclitus" },
  { text: "Day by day, what you do is who you become.", author: "Heraclitus" },
  { text: "Great results require great ambitions.", author: "Heraclitus" },
  { text: "The content of your character is your choice.", author: "Heraclitus" },
  { text: "You cannot escape the results of your thoughts.", author: "James Allen" },
  { text: "To begin, begin.", author: "William Wordsworth" },
  { text: "A mind at peace, a mind centered.", author: "Unknown" },
  { text: "Energy flows where attention goes.", author: "Unknown" },
  { text: "Be the master of your mind, not its slave.", author: "Zen" },
  { text: "One day at a time, one task at a time.", author: "Aura" },
  { text: "Standardize before you optimize.", author: "James Clear" },
  { text: "You do not rise to the level of your goals.", author: "James Clear" },
  { text: "You fall to the level of your systems.", author: "James Clear" },
  { text: "Every action you take is a vote for the person you wish to become.", author: "James Clear" },
  { text: "Focus on the trajectory, not the current results.", author: "James Clear" },
  { text: "Be the designer of your world and not merely the consumer of it.", author: "James Clear" },
  { text: "Environment is the invisible hand that shapes human behavior.", author: "James Clear" },
  { text: "The ultimate form of optimization is elimination.", author: "James Clear" },
  { text: "Professionals stick to the schedule; amateurs let life get in the way.", author: "James Clear" },
  { text: "The most effective way to change your habits is to focus not on what you want to achieve, but on who you wish to become.", author: "James Clear" },
  { text: "Hard work is not enough. You must work on the right things.", author: "Unknown" },
  { text: "The man who has no imagination has no wings.", author: "Muhammad Ali" },
  { text: "Impossible is just a big word thrown around by small men.", author: "Muhammad Ali" },
  { text: "Do not pray for an easy life, pray for the strength to endure a difficult one.", author: "Bruce Lee" },
  { text: "Empty your mind, be formless, shapeless — like water.", author: "Bruce Lee" },
  { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
  { text: "Knowing is not enough, we must apply. Willing is not enough, we must do.", author: "Bruce Lee" },
  { text: "As you think, so shall you become.", author: "Bruce Lee" },
  { text: "Adapt what is useful, reject what is useless, and add what is specifically your own.", author: "Bruce Lee" },
  { text: "A goal is not always meant to be reached; it often serves simply as something to aim at.", author: "Bruce Lee" },
  { text: "Long-term consistency trumps short-term intensity.", author: "Bruce Lee" },
  { text: "Mistakes are always forgivable, if one has the courage to admit them.", author: "Bruce Lee" },
  { text: "To hell with circumstances; I create opportunities.", author: "Bruce Lee" },
  { text: "The key to immortality is first living a life worth remembering.", author: "Bruce Lee" },
  { text: "Simplicity is the key to brilliance.", author: "Bruce Lee" },
  { text: "The more we value things, the less we value ourselves.", author: "Bruce Lee" },
  { text: "It is not a daily increase, but a daily decrease. Hack away at the unessential.", author: "Bruce Lee" },
  { text: "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.", author: "Bruce Lee" },
  { text: "Showing off is the fool's idea of glory.", author: "Bruce Lee" },
  { text: "Be self-aware, rather than a repetitious robot.", author: "Bruce Lee" },
  { text: "Defeat is a state of mind.", author: "Bruce Lee" },
  { text: "If you love life, don't waste time, for time is what life is made up of.", author: "Bruce Lee" },
  { text: "There are no limits. There are only plateaus.", author: "Bruce Lee" },
  { text: "Notice that the stiffest tree is most easily cracked.", author: "Bruce Lee" },
  { text: "While the bamboo or willow survives by bending with the wind.", author: "Bruce Lee" },
  { text: "Real living is living for others.", author: "Bruce Lee" },
  { text: "Persistence is the path to the finish line.", author: "Unknown" },
  { text: "The quietest people have the loudest minds.", author: "Stephen Hawking" },
  { text: "Intelligence is the ability to adapt to change.", author: "Stephen Hawking" },
  { text: "However difficult life may seem, there is always something you can do.", author: "Stephen Hawking" },
  { text: "Work gives you meaning and purpose.", author: "Stephen Hawking" },
  { text: "Look at the stars and not at your feet.", author: "Stephen Hawking" },
  { text: "Success is going from failure to failure without loss of enthusiasm.", author: "Winston Churchill" },
  { text: "Courage is what it takes to stand up and speak.", author: "Winston Churchill" },
  { text: "Courage is also what it takes to sit down and listen.", author: "Winston Churchill" },
  { text: "Continuous effort is the key to unlocking our potential.", author: "Winston Churchill" },
  { text: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill" },
  { text: "The price of greatness is responsibility.", author: "Winston Churchill" },
  { text: "Kites rise highest against the wind.", author: "Winston Churchill" },
  { text: "Success is stumbling from failure to failure.", author: "Winston Churchill" },
  { text: "I never worry about action, but only inaction.", author: "Winston Churchill" },
  { text: "A pessimist sees the difficulty in every opportunity.", author: "Winston Churchill" },
  { text: "An optimist sees the opportunity in every difficulty.", author: "Winston Churchill" },
  { text: "To improve is to change; to be perfect is to change often.", author: "Winston Churchill" },
  { text: "I am an optimist. It does not seem too much use being anything else.", author: "Winston Churchill" },
  { text: "Success is not final, failure is not fatal.", author: "Winston Churchill" },
  { text: "This is the lesson: never give in, never give in, never, never, never.", author: "Winston Churchill" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "You must do the thing you think you cannot do.", author: "Eleanor Roosevelt" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { text: "It is better to light a candle than curse the darkness.", author: "Eleanor Roosevelt" },
  { text: "With the new day comes new strength and new thoughts.", author: "Eleanor Roosevelt" },
  { text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { text: "Yesterday is history, tomorrow is a mystery, today is a gift.", author: "Eleanor Roosevelt" },
  { text: "Character is built in the silence of the night.", author: "Unknown" },
  { text: "True leadership is not about being in charge.", author: "Simon Sinek" },
  { text: "It's about taking care of those in your charge.", author: "Simon Sinek" },
  { text: "Working hard for something we don't care about is called stress.", author: "Simon Sinek" },
  { text: "Working hard for something we love is called passion.", author: "Simon Sinek" },
  { text: "Dream big. Start small. But most of all, start.", author: "Simon Sinek" },
  { text: "The goal is not to do business with everyone who needs what you have.", author: "Simon Sinek" },
  { text: "The goal is to do business with people who believe what you believe.", author: "Simon Sinek" },
  { text: "The value of willpower is not that it can achieve anything.", author: "Unknown" },
  { text: "But that it can resist everything.", author: "Unknown" },
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
  { text: "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.", author: "Abraham Lincoln" },
  { text: "In the end, it's not the years in your life that count.", author: "Abraham Lincoln" },
  { text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
  { text: "I am a slow walker, but I never walk backwards.", author: "Abraham Lincoln" },
  { text: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
  { text: "Things may come to those who wait, but only the things left by those who hustle.", author: "Abraham Lincoln" },
  { text: "Leave nothing for tomorrow which can be done today.", author: "Abraham Lincoln" },
  { text: "I will prepare and some day my chance will come.", author: "Abraham Lincoln" },
  { text: "The leading rule for the lawyer, as for the man of every other calling, is diligence.", author: "Abraham Lincoln" },
  { text: "Extemporaneous speaking should be practiced and cultivated.", author: "Abraham Lincoln" },
  { text: "Commitment is what transforms a promise into reality.", author: "Abraham Lincoln" },
  { text: "I'm a success today because I had a friend who believed in me.", author: "Abraham Lincoln" },
  { text: "We can complain because rose bushes have thorns, or rejoice because thorn bushes have roses.", author: "Abraham Lincoln" },
  { text: "No man has a good enough memory to be a successful liar.", author: "Abraham Lincoln" },
  { text: "Better to remain silent and be thought a fool than to speak and to remove all doubt.", author: "Abraham Lincoln" },
  { text: "I do not think much of a man who is not wiser today than he was yesterday.", author: "Abraham Lincoln" },
  { text: "A drop of honey catches more flies than a gallon of gall.", author: "Abraham Lincoln" },
  { text: "Tact is the ability to describe others as they see themselves.", author: "Abraham Lincoln" },
  { text: "Truth is generally the best vindication against slander.", author: "Abraham Lincoln" },
  { text: "Most folks are as happy as they make up their minds to be.", author: "Abraham Lincoln" },
  { text: "He has a right to criticize, who has a heart to help.", author: "Abraham Lincoln" },
  { text: "Labor is prior to, and independent of, capital.", author: "Abraham Lincoln" },
  { text: "Common looking people are the best in the world.", author: "Abraham Lincoln" },
  { text: "That is why the Lord makes so many of them.", author: "Abraham Lincoln" },
  { text: "I would rather be a little nobody, then to be a evil somebody.", author: "Abraham Lincoln" },
  { text: "Always bear in mind that your own resolution to succeed is more important than any other.", author: "Abraham Lincoln" },
  { text: "Be sure you put your feet in the right place, then stand firm.", author: "Abraham Lincoln" },
  { text: "Those who deny freedom to others, deserve it not for themselves.", author: "Abraham Lincoln" },
  { text: "I am not bound to win, but I am bound to be true.", author: "Abraham Lincoln" },
  { text: "I am not bound to succeed, but I am bound to live up to what light I have.", author: "Abraham Lincoln" },
  { text: "The probability that we may fail in the struggle ought not to deter us.", author: "Abraham Lincoln" },
  { text: "The purpose of life is to live it, to taste experience to the utmost.", author: "Eleanor Roosevelt" },
  { text: "A woman is like a tea bag; you never know how strong it is until it's in hot water.", author: "Eleanor Roosevelt" },
  { text: "It is not fair to ask of others what you are not willing to do yourself.", author: "Eleanor Roosevelt" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt" },
  { text: "Happiness is not in the mere possession of money; it lies in the joy of achievement.", author: "Franklin D. Roosevelt" },
  { text: "I'm not the smartest fellow in the world, but I can sure choose smart colleagues.", author: "Franklin D. Roosevelt" },
  { text: "Men are not prisoners of fate, but only prisoners of their own minds.", author: "Franklin D. Roosevelt" },
  { text: "Competition has been shown to be useful up to a certain point and no further.", author: "Franklin D. Roosevelt" },
  { text: "But cooperation, which is the thing we must strive for today, begins where competition leaves off.", author: "Franklin D. Roosevelt" },
  { text: "To reach a port we must set sail.", author: "Franklin D. Roosevelt" },
  { text: "Sail, not tie at anchor. Sail, not drift.", author: "Franklin D. Roosevelt" },
  { text: "Courage is not the absence of fear, but rather the assessment that something else is more important.", author: "Franklin D. Roosevelt" },
  { text: "Rules are not necessarily sacred, principles are.", author: "Franklin D. Roosevelt" },
  { text: "True individual freedom cannot exist without economic security and independence.", author: "Franklin D. Roosevelt" },
  { text: "Necessitous men are not free men.", author: "Franklin D. Roosevelt" },
  { text: "Physical strength can never permanently withstand the impact of spiritual force.", author: "Franklin D. Roosevelt" },
  { text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
  { text: "We have always held to the hope, the belief, the conviction that there is a better life.", author: "Franklin D. Roosevelt" },
  { text: "Human kindness has never weakened the stamina or softened the fiber of a free people.", author: "Franklin D. Roosevelt" },
  { text: "There is nothing I love as much as a good fight.", author: "Franklin D. Roosevelt" },
  { text: "A nation that destroys its soils destroys itself.", author: "Franklin D. Roosevelt" },
  { text: "The self is not something one finds, it is something one creates.", author: "Thomas Szasz" },
  { text: "Your life does not get better by chance, it gets better by change.", author: "Jim Rohn" },
  { text: "The major value in life is not what you are going to get.", author: "Jim Rohn" },
  { text: "The major value in life is what you are going to become.", author: "Jim Rohn" },
  { text: "Formal education will make you a living; self-education will make you a fortune.", author: "Jim Rohn" },
  { text: "If you don't design your own life plan, chances are you'll fall into someone else's plan.", author: "Jim Rohn" },
  { text: "And guess what they have planned for you? Not much.", author: "Jim Rohn" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "Success is nothing more than a few simple disciplines, practiced every day.", author: "Jim Rohn" },
  { text: "Either you run the day or the day runs you.", author: "Jim Rohn" },
  { text: "Learn how to be happy with what you have while you pursue all that you want.", author: "Jim Rohn" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "Motivation alone is not enough. If you have an idiot and you motivate him.", author: "Jim Rohn" },
  { text: "Now you have a motivated idiot.", author: "Jim Rohn" },
  { text: "Happiness is not something you postpone for the future; it is something you design for the present.", author: "Jim Rohn" },
  { text: "Profit is better than wages.", author: "Jim Rohn" },
  { text: "Wages make you a living, profits make you a fortune.", author: "Jim Rohn" },
  { text: "Character is a quality that embodies many important traits, such as integrity and courage.", author: "Jim Rohn" },
  { text: "We must all suffer one of two things: the pain of discipline or the pain of regret.", author: "Jim Rohn" },
  { text: "The few who do are the envy of the many who only watch.", author: "Jim Rohn" },
  { text: "Don't wish it were easier, wish you were better.", author: "Jim Rohn" },
  { text: "Days are expensive. When you spend a day you have one less day to spend.", author: "Jim Rohn" },
  { text: "Make sure you do not spend a dollar's worth of time on a ten-cent task.", author: "Jim Rohn" },
  { text: "If you want to be a leader who attracts quality people, the key is to become a person of quality yourself.", author: "Jim Rohn" },
  { text: "The more you care, the stronger you can be.", author: "Jim Rohn" },
  { text: "Walls turned sideways are bridges.", author: "Angela Davis" },
  { text: "I am no longer accepting the things I cannot change.", author: "Angela Davis" },
  { text: "I am changing the things I cannot accept.", author: "Angela Davis" },
  { text: "You have to act as if it were possible to radically transform the world.", author: "Angela Davis" },
  { text: "And you have to do it all the time.", author: "Angela Davis" },
  { text: "Radical simply means 'grasping things at the root'.", author: "Angela Davis" },
  { text: "The source of every new idea is the same.", author: "Jonah Lehrer" },
  { text: "A network of neurons which has never fired together is now firing together.", author: "Jonah Lehrer" },
  { text: "Insight is not a lightbulb in the void; it is a spark in the architecture.", author: "Jonah Lehrer" },
  { text: "Creative people are better at seeing the connections.", author: "Steve Jobs" },
  { text: "Design is a funny word.", author: "Steve Jobs" },
  { text: "Some people think design means how it looks.", author: "Steve Jobs" },
  { text: "But of course, if you dig deeper, it's really how it works.", author: "Steve Jobs" },
  { text: "Real artists ship.", author: "Steve Jobs" },
  { text: "I want to put a ding in the universe.", author: "Steve Jobs" },
  { text: "Focusing is about saying no.", author: "Steve Jobs" },
  { text: "The only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs" },
  { text: "And the only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "If you haven't found it yet, keep looking. Don't settle.", author: "Steve Jobs" },
  { text: "As with all matters of the heart, you'll know when you find it.", author: "Steve Jobs" },
  { text: "Be a yardstick of quality. Some people aren't used to an environment where excellence is expected.", author: "Steve Jobs" },
  { text: "Your work is going to fill a large part of your life.", author: "Steve Jobs" },
  { text: "Sometimes life hits you in the head with a brick. Don't lose faith.", author: "Steve Jobs" },
  { text: "My model for business is The Beatles.", author: "Steve Jobs" },
  { text: "They were four guys who kept each other's kind of negative tendencies in check.", author: "Steve Jobs" },
  { text: "They balanced each other and the total was greater than the sum of the parts.", author: "Steve Jobs" },
  { text: "That's how I see business: great things in business are never done by one person.", author: "Steve Jobs" },
  { text: "They're done by a team of people.", author: "Steve Jobs" },
  { text: "Aura: Flow follows focus.", author: "System" }
];
